# Generated by Django 4.0.3 on 2022-04-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer',
            new_name='stripe_customer_id',
        ),
    ]
